spring:
    security:
       oauth2:
          client:
              registration:
                  azure:
                      client-id: ea431e05-7196-42c8-b6cd-4b0af33191cc
                      client-secret: o7r9+Tk3+gi/GzNFOKWMTNHZhpdF/bY1O6WK+1kJFG8=
    datasource:
      url: jdbc:mysql://localhost:3306/authuser?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Start123

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8080

azure:
    activedirectory:
        tenant-id: 94058894-8314-415d-9482-8d3b9eea4888
        active-directory-groups: users,admins

rest:
  endpoint:
    person: localhost:8081/person